#!/usr/bin/env python3
"""Regenerate every manifest of this release repo from the artifacts on disk.

    tools/mkmanifest.py [c] [rs] [--product P] [--base-url URL]

Writes <product>/<variant>/releases.txt for each variant (default: every
variant directory present) and the top-level releases.txt, all UNSIGNED.
Any releases.sig whose manifest changed is deleted — it no longer matches —
so the next step is always tools/sign.py.

Artifact names (what tools/mkreleases.py writes):
  binaries/  {product}-{variant}-v{ver}-{arch}-linux-{static|gnu|musl}.tar.gz
             (static = fully static, listed with libc "any")
  sources/   {product}-{variant}-v{ver}-src.tar.gz

Per-version metadata comes from {product}/{variant}/meta.tsv
(version, date, src_deps, min_from).  A version found on disk without a row
gets one here (date = today, min_from = '*'), so a later regeneration never
re-dates it.  src_deps is for source rows only: a binary row always carries
'none', or the updater would demand a compiler to install a prebuilt binary.

Rows in an existing releases.txt whose URL is not under this repo (e.g. a
GitHub tag archive listed by hand) are kept as they are.
"""
import argparse
import glob
import hashlib
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import relcommon as rc  # noqa: E402

HEADER = """\
# {product} {variant} release manifest — Ed25519-signed (see ../../SIGNING.md)
# Generated by tools/mkmanifest.py — edit meta.tsv / the artifacts, not this file.
# Columns (whitespace-separated). The FIRST FIVE are the legacy format and
# stay parseable by the pre-existing updater (sscanf ...==5); trailing
# columns are read only by the network-upgrade-aware daemon.
#   1 version    e.g. v2.3.0   (leading 'v' optional; compared with 'v' stripped)
#   2 date       YYYY-MM-DD
#   3 url        artifact download URL (https+github OR the local-source override)
#   4 sha256     lowercase hex of the artifact
#   5 deps       comma list for src builds; 'none' for prebuilt binaries
#   6 kind       bin | src
#   7 arch       x86_64 | any        (any = arch-independent, e.g. src)
#   8 libc       gnu | musl | any
#   9 min_from   oldest version this artifact may upgrade FROM ('*' = any)
#  10 cpu        CPU features it needs ('-' = none; 'arch:feat' = only on arch)
"""

TOP_HEADER = """\
# {product} top-level manifest — lists versions x variants (c, rs).
# Ed25519-signed (releases.sig). Points at per-variant manifests.
# Generated by tools/mkmanifest.py.
# columns: version  variant  codebase_manifest_path  min_from
"""


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def read_bytes(path):
    try:
        with open(path, "rb") as f:
            return f.read()
    except FileNotFoundError:
        return None


def write_manifest(path, text):
    """Write if changed; drop a signature that no longer covers the bytes."""
    rel = os.path.relpath(path, rc.ROOT)
    data = text.encode()
    sig = os.path.join(os.path.dirname(path), "releases.sig")
    if read_bytes(path) == data:
        state = "signed" if os.path.exists(sig) else "UNSIGNED"
        print(f"  unchanged  {rel}  ({state})")
        return False
    with open(path + ".tmp", "wb") as f:
        f.write(data)
    os.replace(path + ".tmp", path)
    if os.path.exists(sig):
        os.remove(sig)
        print(f"  wrote      {rel}  (stale releases.sig removed)")
    else:
        print(f"  wrote      {rel}")
    return True


def variant_rows(prod, variant, base):
    vd = rc.vdir(prod, variant)
    meta_path = os.path.join(vd, "meta.tsv")
    meta = rc.meta_load(meta_path)
    ours = f"{base}/{prod}/{variant}/"
    binre = re.compile(rf"^{re.escape(prod)}-{re.escape(variant)}-v([0-9][0-9A-Za-z.\-]*)"
                       rf"-([a-z0-9_]+)-linux-({'|'.join(rc.LIBC_LABELS)})\.tar\.gz$")
    srcre = re.compile(rf"^{re.escape(prod)}-{re.escape(variant)}-v([0-9][0-9A-Za-z.\-]*)-src\.tar\.gz$")

    found = []   # (ver, kind, name, arch, libc)
    for path in sorted(glob.glob(os.path.join(vd, "binaries", "*.tar.gz"))):
        name = os.path.basename(path)
        m = binre.match(name)
        if not m:
            print(f"  skip (name) {variant}/binaries/{name}", file=sys.stderr)
            continue
        found.append(("v" + m.group(1), "bin", name, m.group(2), rc.manifest_libc(m.group(3))))
    for path in sorted(glob.glob(os.path.join(vd, "sources", "*.tar.gz"))):
        name = os.path.basename(path)
        m = srcre.match(name)
        if not m:
            print(f"  skip (name) {variant}/sources/{name}", file=sys.stderr)
            continue
        found.append(("v" + m.group(1), "src", name, "any", "any"))

    added = [v for v in sorted({f[0] for f in found}, key=rc.verkey) if v not in meta]
    for v in added:
        meta[v] = [rc.today(), rc.PRODUCTS[prod][variant]["src_deps"], "*"]
    if added:
        rc.meta_save(meta_path, meta)
        print(f"  meta.tsv   {variant}: added {', '.join(added)}")

    rows = []
    for ver, kind, name, arch, libc in found:
        date, deps, minf = meta[ver]
        path = os.path.join(vd, "binaries" if kind == "bin" else "sources", name)
        deps = "none" if kind == "bin" else (deps or rc.PRODUCTS[prod][variant]["src_deps"])
        url = f"{ours}{'binaries' if kind == 'bin' else 'sources'}/{name}"
        rows.append([ver, date or rc.today(), url, sha256(path), deps, kind, arch, libc,
                     minf or "*", rc.cpu_needs(variant, arch)])

    # Keep hand-listed rows that point somewhere else (not regenerable from disk).
    kept = []
    old = read_bytes(os.path.join(vd, "releases.txt"))
    for line in (old or b"").decode().splitlines():
        f = line.split()
        if line.startswith("#") or len(f) < 5 or f[2].startswith(ours):
            continue
        if not re.fullmatch(r"[0-9a-f]{64}", f[3]) or f[3] == "0" * 64:
            print(f"  dropped    {variant}: placeholder row {f[0]} {f[2]} (no real sha256)",
                  file=sys.stderr)
            continue
        kept.append((f + ["src", "any", "any", "*", "-"][max(0, len(f) - 5):])[:10])
    if kept:
        print(f"  kept       {variant}: {len(kept)} external row(s) "
              f"({', '.join(sorted({k[0] for k in kept}, key=rc.verkey))})")
    rows += kept

    # A meta row with nothing behind it is harmless but usually a typo.
    orphan = sorted(set(meta) - {r[0] for r in rows}, key=rc.verkey)
    if orphan:
        print(f"  note       {variant}: meta.tsv lists {', '.join(orphan)} with no artifact",
              file=sys.stderr)

    rows.sort(key=lambda r: (rc.verkey(r[0]), r[5], r[6], r[7]))
    return rows, meta


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("variants", nargs="*", metavar="c|rs",
                    help="variants to regenerate (default: every variant dir present)")
    ap.add_argument("--product", help="override the product taken from the repo name")
    ap.add_argument("--base-url", help="URL the repo is served from "
                    "(default: the raw.githubusercontent.com URL the daemons compile in)")
    a = ap.parse_args()
    sys.stdout.reconfigure(line_buffering=True)   # keep order with stderr notes

    prod = rc.product(a.product)
    bad = [v for v in a.variants if v not in rc.VARIANTS]
    if bad:
        rc.die(f"unknown variant(s) {', '.join(bad)} (c, rs)")
    base = (a.base_url or rc.raw_base(prod)).rstrip("/")
    present = [v for v in rc.VARIANTS if os.path.isdir(rc.vdir(prod, v))]
    variants = [v for v in present if v in a.variants] if a.variants else present

    top = []   # (ver, variant, min_from) over every variant, not only the regenerated ones
    for v in present:
        if v in variants:
            rows, meta = variant_rows(prod, v, base)
            text = HEADER.format(product=prod, variant=v) + "".join(" ".join(r) + "\n" for r in rows)
            write_manifest(os.path.join(rc.vdir(prod, v), "releases.txt"), text)
            print(f"             {v}: {len(rows)} artifact row(s)")
        else:
            meta = rc.meta_load(os.path.join(rc.vdir(prod, v), "meta.tsv"))
            old = read_bytes(os.path.join(rc.vdir(prod, v), "releases.txt")) or b""
            rows = [l.split() for l in old.decode().splitlines()
                    if l and not l.startswith("#") and len(l.split()) >= 5]
        for ver in sorted({r[0] for r in rows}, key=rc.verkey):
            top.append((ver, v, (meta.get(ver) or ["", "", "*"])[2] or "*"))

    top.sort(key=lambda t: (rc.verkey(t[0]), rc.VARIANTS.index(t[1])))
    text = TOP_HEADER.format(product=prod) + "".join(
        f"{ver} {v} {prod}/{v}/releases.txt {minf}\n" for ver, v, minf in top)
    write_manifest(os.path.join(rc.ROOT, "releases.txt"), text)

    unsigned = [os.path.relpath(p, rc.ROOT) for p in rc.manifests(prod)
                if not os.path.exists(os.path.join(os.path.dirname(p), "releases.sig"))]
    if unsigned:
        print(f"\nnext: tools/sign.py <private-key>   (unsigned: {', '.join(unsigned)})")
    else:
        print("\nevery manifest is signed — tools/sign.py --verify, then commit + push")


if __name__ == "__main__":
    main()
